spring:
  application:
    name: webflux1-practice

  r2dbc:
    url: r2dbc:mysql://localhost:3307/r2dbc
    username: root
    password: root

  data:
    redis:
      host: localhost
      port:  6379

logging:
  level:
    root: info

